@startuml
title Activity Diagram 

start
:User enters login and password;
:Program analyzes entered user data;
if (Is data correct?) then (Yes)
  :Correct;
else (No)
  :Error: Invalid data;
  --> User enters login and password
endif
stop

@enduml
